config/routes.rb
Mandarin::Application.routes.draw do

  resources :users

  get   '/login', :to => 'sessions#new', :as => :login
  match '/sign_up', :to => 'users#new', :as => :sign_up
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/sign_in', :to => 'sessions#create', :as => 'sign_in'
  match '/auth/failure', :to => 'sessions#failure'
  delete '/logout', :to => 'sessions#destroy'
  get '/search', :to => 'welcome#search'

  root :to => 'welcome#index'

end

app/models/auth_user.rb
class AuthUser < ActiveRecord::Base
  has_many :authorizations, :foreign_key => :user_id
  set_table_name "users"
  attr_accessible :email, :name

  validates :name, :presence => :true
  validates :email, :presence => :true, :uniqueness => :true, :on => :update
  def add_provider(auth_hash)
  # Check if the provider already exists, so we don't add it twice
  unless authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
    authorizations.create :provider => auth_hash["provider"], :uid => auth_hash["uid"]
  end
end


end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  attr_accessible :provider, :uid, :user_id
  belongs_to :user

  validates :provider, :uid, :presence => true

  scope :find_by_auth, lambda { |auth_hash| where("provider = ? AND uid = ?" , auth_hash["provider"], auth_hash["uid"]) }

  #def self.find_(auth_hash)
    #find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
  #end
  def self.create_(auth_hash)
    user = AuthUser.create :name => auth_hash["info"]["name"], "email" => auth_hash["info"]["email"]
    auth = create :user_id => user.id, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password

  has_many :authorizations
  validates :name, :presence => :true
  validates :email, :presence => :true, :uniqueness => :true, :on => :update
  validates :email, :presence => :true, :uniqueness => :true, :on => :sign_up
  validates_confirmation_of :password
  validates :password, :presence => :true, :on => :create

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user
  before_filter :require_email

  def require_email
    if current_user && current_user.email.blank?
      redirect_to edit_user_path(session[:user_id])
    end
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :require_email, :only => :destroy

  def new
  end

  def create
    if auth_hash = request.env['omniauth.auth']
      if session[:user_id]
        # Means our user is signed in. Add the authorization to the user
        AuthUser.find(session[:user_id]).add_provider(auth_hash)

      # render :text => "You can now login using #{auth_hash["provider"].capitalize} too!"
      else
        # Log him in or sign him up
        if @auth = Authorization.find_by_auth(auth_hash).first
          redirect_to root_url
          flash[:notice] = "Welcome back #{@auth.user.name}"
          # Create the session
          session[:user_id] = @auth.user.id
        else
          @auth = Authorization.create_(auth_hash)
          redirect_to edit_user_url(@auth.user)
        end
      session[:user_id] = @auth.user.id
      end

    elsif user = User.authenticate(params[:email], params[:password])
      if user
        session[:user_id] = user.id
        flash[:notice] = "Logged in!"
      end
    else
        flash.now.alert = "Invalid email or password"
        return
    end
  @user = User.find(session[:user_id]).name
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out!"
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :require_email, :except => :show

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.valid?(:sign_up)
      @user.save
    end
  end

  def update
    @user = User.find(params[:id])
    if @user and @user.update_attributes(params[:user])
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mandarin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
  <div id="myModal" class="hide modal fade">
  </div>
</body>
</html>

app/views/users/_form.html.erb
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Sign up nahren!</h3>
</div>
      <%= form_for(@user, :url => { :action => :create }, :remote => :true) do |f| %>
<div class="modal-body">
        <% if @user.errors.any? %>
          <div class="error messages">
            <p>Form is invalid</p>
            <ul>
              <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :email %>
        <%= f.email_field :email %>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation %>
</div>
<div class="modal-footer">
  <div class="form_actions">
      <%= f.submit "Sign up", :class => "btn btn-primary" %>
    <% end %>
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </div>
</div>

app/views/users/create.js.erb
<% if @user.valid?(:sign_up) %>
  window.location = "<%= root_url %>"
<% else %>
  $('#myModal').html("<%= j(render partial: 'form') %>");
  $('#myModal').modal();
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= form_for @user, :url => { :action => :update, :id => @user.id } do |f| %>
  <div class="control-group">
    <%= f.label :name, "Name: ", class: "control-label" %>
    <%= f.text_field :name %>
  </div>
  <div class="control-group">
    <%= f.label :email, "E-mail: ", class: "control-label" %>
    <%= f.text_field :email %>
  </div>
  <div class="control-grop controls">
    <%= f.submit %>
  </p>
<% end %>

app/views/users/new.js.erb
$('#myModal').html("<%= j(render partial: 'form') %>");
  $('#myModal').modal();

app/views/users/show.html.erb
<%= @user.name %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/index.html.erb
<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>
  <h1>Welcome to Mandarin</h1>
  <% if current_user %>
    <p>You are logged in as <%= current_user.name %><br/><%= link_to "Logout", logout_path, :method => :delete %></p>
  <% else %>
    <p><%= link_to "Login", login_path, :remote => :true %> or <%= link_to "Sign up", sign_up_path, :remote => :true %></p>
  <% end %>